name: Publish Packages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
          
      - name: Install Dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish Dmime
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
          PROJECT_FILE_PATH: src/Dmime/Dmime.csproj
          NUGET_KEY: ${{secrets.Nuget_API_Key}}
          NUGET_SOURCE: https://api.nuget.org

      - name: Publish Dmime.Extensions.MicrosoftDependencyInjection
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
          PROJECT_FILE_PATH: src/Dmime.Extensions.MicrosoftDependencyInjection/Dmime.Extensions.MicrosoftDependencyInjection.csproj
          NUGET_KEY: ${{secrets.Nuget_API_Key}}
          NUGET_SOURCE: https://api.nuget.org